version: '3.4'
services:
  web:
    #image:
    container_name: discord-bot-rust
    network_mode: "host"
    build:
      context: .
      target: builder
    command: cargo run --release
    ports:
      - "9003:9003"
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=error,rfcbot=debug

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml